% use make_masterTable(true,false);
function make_masterTable(overwrite,backup)
if overwrite || ~isfile('Tmaster.txt')
    variable_names_types = [["filename", "string"]; ...
                ["day", "datetime"]; ...
                ["awake", "datetime"]; ...
                ["exit_nest", "datetime"]; ...
                ["enter_nest", "datetime"]; ...
                ["asleep", "datetime"]];
    % Make table using fieldnames & value types from above
    Tmaster = table('Size',[0,size(variable_names_types,1)],... 
        'VariableNames', variable_names_types(:,1),...
        'VariableTypes', variable_names_types(:,2));
    if backup
        movefile('Tmaster.txt',['Tmaster',datestr(now,'yyyymmddHHMM'),'.txt']);
    end
    writetable(Tmaster,'Tmaster');
end